dist: trusty
sudo: required 
language: cpp
os:
- linux
branches:
  only:
  - master
env:
  global:
    - ARDUINO_IDE_VERSION=1.8.4
install:
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_ide_install.sh;
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./install_googletest.sh;
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./install_rapidassist.sh;
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./install_win32arduino.sh;
script:
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh Countdown
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh CycleHighPin
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh FadeLed
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh ProgressBar
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh StateMachine
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh ToggleLed
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./arduino_build_sketch.sh ToggleLedAdvanced
  - cd $TRAVIS_BUILD_DIR/ci/travis; ./build_library.sh;
  - cd $TRAVIS_BUILD_DIR/build/bin;
    ./softtimers_unittest || true; #do not fail build even if a test fails.
notifications:
  email: true
