# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
# version must contains build number to make sure that all commits are processed by appveyor.
# If build number is not part of the version than appveyor build fails with the following message: "Build version x.y.z already exists."
version: "{branch} (#{build})"

# branches to build
branches:
  only:
    - prerelease-1.2.0

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)

# clone directory
clone_folder: c:\projects\SoftTimers

# scripts that run after cloning repository
install:
- cmd: set APPVEYOR_BUILD_VERSION=1.2.0
- ps: .\ci\appveyor\generate_environment.ps1
- cmd: call .\ci\appveyor\environment.bat
- ps: .\ci\appveyor\prepare_github_deploy.ps1
- cmd: call c:\projects\SoftTimers\ci\appveyor\version_info_update.bat
- cmd: call c:\projects\SoftTimers\ci\appveyor\googletest_install.bat
- cmd: call c:\projects\SoftTimers\ci\appveyor\googletest_build.bat
- cmd: call c:\projects\SoftTimers\ci\appveyor\win32arduino_install.bat
- cmd: call c:\projects\SoftTimers\ci\appveyor\win32arduino_build.bat

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform: x86

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

before_build:
- cmd: call c:\projects\SoftTimers\cmake\vs2010.bat

build:
  project: cmake\build\softtimers.sln
  verbosity: minimal

after_build:
- cmd: del c:\projects\SoftTimers\src\SoftTimers\CMakeLists.txt
- cmd: call c:\projects\SoftTimers\ci\appveyor\build_deploy_package.bat
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
- cmd: call c:\projects\SoftTimers\ci\appveyor\test_script.bat

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: cmake\build\bin\Release\SoftTimers_unittest.x86.release.xml
  name: SoftTimers_unittest.x86.release.xml
- path: deploy\*.zip
  name: SoftTimers portable
  
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

#prepare deplying to github. See prepare_github_deploy.ps1 for more details.
deploy:
- provider: GitHub
  tag: $(GITHUB_TAG_NAME)
  release: $(GITHUB_RELEASE_NAME)
  description: Latest successful AppVeyor CI builds of branch '$(APPVEYOR_REPO_BRANCH)', commit $(APPVEYOR_REPO_COMMIT)
  auth_token:
    secure: BgyLisMc154qWpkyBdh8OD+D9HMM+YnBkh7H4MEUShKO3aCU+Fn/XVGJ07fTsRmH
  artifact: /(.*\.zip|.*\.exe)/
  draft: false           #true means release is private (visible to contributors only), false is public (visible to everyone)
  prerelease: false      #true for prerelease, false to identify this release as the 'latest release'
  force_update: true
