#ifndef SOFTTIMERS_VERSION_H
#define SOFTTIMERS_VERSION_H

#define SOFTTIMERS_MAJOR_VERSION 1
#define SOFTTIMERS_MINOR_VERSION 3
#define SOFTTIMERS_PATCH_VERSION 0
#define SOFTTIMERS_VERSION_STRING "1.3.0"

#endif //SOFTTIMERS_VERSION_H
